// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gydbuskhgzpeoqmqzeij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZGJ1c2toZ3pwZW9xbXF6ZWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1NDQ2NjYsImV4cCI6MjA4MDEyMDY2Nn0.HCOofsTL7iQ25_UbHkjg24oM5wpMvDXerJXeLqd_6bM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});